# -*- coding: utf-8 -*-
"""BertApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GerUErLZf_bSbSgzYWS73foQRj-NRvdw
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
from transformers import AutoModelForQuestionAnswering, AutoTokenizer, pipeline

app = Flask(__name__)
CORS(app)  # Enable CORS for cross-origin requests

# Load BioBERT Model
MODEL_NAME = "dmis-lab/biobert-large-cased-v1.1"
biobert_model = AutoModelForQuestionAnswering.from_pretrained(MODEL_NAME)
biobert_tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
qa_pipeline = pipeline("question-answering", model=biobert_model, tokenizer=biobert_tokenizer)

@app.route("/", methods=["GET"])
def home():
    return jsonify({"message": "BioBERT API is running!"})

@app.route("/predict", methods=["POST"])
def predict():
    data = request.get_json()
    question = data.get("question")
    context = data.get("context")

    if not question or not context:
        return jsonify({"error": "Both 'question' and 'context' fields are required"}), 400

    result = qa_pipeline(question=question, context=context)
    return jsonify({"answer": result["answer"], "score": result["score"]})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)  # Default Render setup
